networks:
  default:

volumes:
  data:
    driver: local

services:
  database:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - data:/var/lib/postgresql/data

  server:
    image: reaktor-summer-2022-server:1
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/postgres?user=postgres&password=postgres&ApplicationName=reaktor-summer-2022
    depends_on:
      - database

  client:
    image: reaktor-summer-2022-client:1
    environment:
      - API_URL=http://server:8080
    ports:
      - "3005:3000"
    depends_on:
      - server
